# Generated by Django 3.2.6 on 2021-08-17 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0033_alter_productmodel_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='wishlist'),
        ),
    ]
