# Generated by Django 3.2.6 on 2021-08-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_remove_productmodel_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='height',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.heightmodel', verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sku',
            field=models.IntegerField(blank=True, null=True, verbose_name='sku'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.weightmodel', verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='width',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.widthmodel', verbose_name='width'),
        ),
    ]
