# Generated by Django 3.2.6 on 2021-08-20 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20210820_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='height',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.heightmodel', verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sku',
            field=models.IntegerField(null=True, verbose_name='sku'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.weightmodel', verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='width',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.widthmodel', verbose_name='width'),
        ),
    ]
