# Generated by Django 3.2.6 on 2021-08-23 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20210820_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='height',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.heightmodel', verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='products.ProductTagModel', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.weightmodel', verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='width',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.widthmodel', verbose_name='width'),
        ),
    ]
