# Generated by Django 3.2.6 on 2021-08-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20210823_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='single_product_description',
            field=models.TextField(null=True, verbose_name='single_product_description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.ProductTagModel', verbose_name='tags'),
        ),
    ]
