# Generated by Django 3.2.6 on 2021-08-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_alter_productmodel_single_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='single_product_description',
            field=models.TextField(null=True, verbose_name='single_product_description'),
        ),
    ]
