# Generated by Django 3.2.6 on 2021-08-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_remove_productmodel_single_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='brand',
        ),
    ]
