# Generated by Django 3.2.6 on 2021-08-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_productmodel_product_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_long_description_en',
            field=models.TextField(max_length=30, null=True, verbose_name='product_long_description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_long_description_ru',
            field=models.TextField(max_length=30, null=True, verbose_name='product_long_description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_long_description_uz',
            field=models.TextField(max_length=30, null=True, verbose_name='product_long_description'),
        ),
    ]
