# Generated by Django 3.2.6 on 2021-08-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_auto_20210829_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_long_description',
            field=models.TextField(max_length=86, null=True, verbose_name='product_long_description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_long_description_en',
            field=models.TextField(max_length=86, null=True, verbose_name='product_long_description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_long_description_ru',
            field=models.TextField(max_length=86, null=True, verbose_name='product_long_description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_long_description_uz',
            field=models.TextField(max_length=86, null=True, verbose_name='product_long_description'),
        ),
    ]
