# Generated by Django 3.2.6 on 2021-08-31 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0048_auto_20210830_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='wishlist'),
        ),
    ]
