# Generated by Django 3.2.6 on 2021-09-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_productmodel_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandModel',
        ),
    ]
